### ISSUE TITLE
Unable To Generate MonoRepo Configurations

### ISSUE THREAD

**Issue by tmack8001** [renovatebot/presets#170]
When attempting to generate the source for monorepo configuration I get the following error:

```
node generate
internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module '@sindresorhus/is'
Require stack:
- .../renovatebot/presets/packages/renovate-config-monorepo/generate.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (.../renovatebot/presets/packages/renovate-config-monorepo/generate.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '.../renovatebot/presets/packages/renovate-config-monorepo/generate.js'
  ]
}
```

Not the only user getting this error as @tomkerkhove also reported it here, https://github.com/renovatebot/presets/pull/169

**Comment by rarkins** [comment]
I've added the lib to the `package.json` in the root directory of this repo. You need to run `yarn` here before running any generator commands within sub-packages. The same lib was already a transitive dependency of `renovate` itself but it's better to make it explicit.

**Comment by tomkerkhove** [comment]
Thanks for the fix!

**Comment by tmack8001** [comment]
@rarkins should we update the readme.md to reference that need?
https://github.com/renovatebot/presets/tree/master/packages/renovate-config-monorepo#contributing just says to run `node generate`

**Comment by tomkerkhove** [comment]
I still have the same issue:
![image](https://user-images.githubusercontent.com/4345663/75545954-df9c2c80-5a27-11ea-8119-1aca95e8e192.png)

**Comment by rarkins** [comment]
It looks like you’re running the install in the subdirectory instead of root directory

**Comment by tomkerkhove** [comment]
Good point, sorry!
